version: '3.9'

services:
    mysql:
        image: mysql/mysql-server:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - memento-mysql:/var/lib/mysql
            - ./memento-back.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - memento-network
        expose:
          - '3306'
        healthcheck:
            test: [
                'CMD',
                'mysqladmin',
                'ping',
                '-p${DB_PASSWORD}'
            ]
            retries: 3
            timeout: 5s
    
    php:
        build: ./memento-php
        user: root
        volumes:
            - memento:/memento
        networks:
            - memento-network

    nginx:
        user: root
        build: 
            context: ..
            dockerfile: production/memento-nginx/Dockerfile
        ports:
            - 8080:80
        volumes:
            - memento:/memento
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        links:
            - php
        networks:
            - memento-network

networks:
    memento-network:
        driver: bridge

volumes:
    memento-mysql:
        driver: local
    memento:
